exports.cmds = [
    [`clear screen`],
    [`SELECT * `, `FROM tab;`],
    [`SELECT * `, `FROM countries;`],
    [`SELECT * `, `FROM departments;`],
    [`SELECT * `, `FROM employees;`],
    [`SELECT * `, `FROM emp_details_view;`],
    [`SELECT * `, `FROM jobs;`],
    [`SELECT * `, `FROM job_history;`],
    [`SELECT * `, `FROM locations;`],
    [`SELECT * `, `FROM regions;`],
    [`SELECT last_name, job_id, department_id`, `FROM employees`, `WHERE last_name = 'Whalen' ;`],
    [
        `SELECT  AVG(salary), MAX(salary),`,
        `        MIN(salary), SUM(salary)`,
        `FROM employees`,
        `WHERE job_id LIKE '%REP%';`,
    ],
    [`SELECT MIN(hire_date), MAX(hire_date)`, `FROM employees;`],
    [`SELECT COUNT(*)`, `FROM employees`, `WHERE department_id = 50;`],
    [`SELECT COUNT(commission_pct)`, `FROM employees`, `WHERE department_id = 80;`],
    [`SELECT COUNT(DISTINCT department_id)`, `FROM employees;`],
    [`SELECT AVG(commission_pct)`, `FROM employees;`],
    [`SELECT AVG(NVL(commission_pct, 0))`, `FROM employees;`],
    [`SELECT department_id, AVG(salary)`, `FROM employees`, `GROUP BY department_id`, `ORDER BY department_id ;`],
    [`SELECT AVG(salary)`, `FROM employees`, `GROUP BY department_id ;`],
    [
        `SELECT department_id, job_id, SUM(salary)`,
        `FROM employees`,
        `WHERE department_id > 40`,
        `GROUP BY department_id, job_id `,
        `ORDER BY department_id;`,
    ],
    [`SELECT department_id, MAX(salary)`, `FROM employees`, `GROUP BY department_id`, `HAVING MAX(salary) > 10000 ;`],
    [
        `SELECT job_id, SUM(salary) PAYROLL`,
        `FROM employees`,
        `WHERE job_id NOT LIKE '%REP%'`,
        `GROUP BY job_id`,
        `HAVING SUM(salary) > 13000`,
        `ORDER BY SUM(salary);`,
    ],
    [`SELECT MAX(AVG(salary))`, `FROM employees`, `GROUP BY department_id;`],
    [
        `SELECT e.last_name, e.department_id, d.department_name`,
        `FROM employees e LEFT OUTER JOIN departments d`,
        `ON (e.department_id = d.department_id) ;`,
    ],
    [
        `SELECT e.last_name, d.department_id, d.department_name`,
        `FROM employees e RIGHT OUTER JOIN departments d`,
        `ON (e.department_id = d.department_id) ;`,
    ],
    [
        `SELECT e.last_name, d.department_id, d.department_name`,
        `FROM employees e FULL OUTER JOIN departments d`,
        `ON (e.department_id = d.department_id) ;`,
    ],
    [`SELECT last_name, department_name`, `FROM employees`, `CROSS JOIN departments ;`],
    [
        `SELECT last_name, salary`,
        `FROM employees`,
        `WHERE salary >`,
        `        (SELECT salary`,
        `        FROM employees`,
        `        WHERE last_name = 'Abel');`,
    ],
    [
        `SELECT last_name, job_id, salary`,
        `FROM employees`,
        `WHERE job_id = `,
        `        (SELECT job_id FROM employees`,
        `        WHERE first_name = 'Jonathon')`,
        `AND salary >`,
        `        (SELECT salary FROM employees`,
        `        WHERE first_name = 'Jonathon');`,
    ],
    [
        `SELECT last_name, job_id, salary`,
        `FROM employees`,
        `WHERE salary = `,
        `        (SELECT MIN(salary)`,
        `        FROM employees);`,
    ],
    [`LIST`],
    [`/`],
];
